### PR TITLE
Streamline CI

### PR DESCRIPTION
**Pull request by shym**
As a follow-up to the previous PR, this one adds two new CI workflows for the bytecode version on Windows and the corresponding badges. It also removes some remaining mentions of `rc1`, drops the alpha opam repository (which is no longer necessary with the release of OCaml 5) and logs the opam repositories from which dependencies are pulled (to make sure the multiple opam repositories are indeed providing exactly the packages they are expected to provide, and not conflicting with the main default one).

### CODE REVIEW

**Comment by jmid** [comment]
PR looks great - thanks!
I'll let the CI run finish and then merge. The early macOS failure looks like a temporary network hiccup.

**Comment by jmid** [comment]
This looks a lot greener! :smiley:  ... but it does include a Win bytecode crash! :grimacing: 
If nothing else, this looks relatively easy to trigger consistently? :thinking:

**Comment by shym** [comment]
Indeed, I see many many deadlocks, maybe the bytecode version is the right one to try and finally corner that bug (if it’s indeed #203 since PR11846 seems to fix-or-hide it in native)

**Comment by jmid** [comment]
OK, so we have
- a windows bytecode crash
- a windows threadomain timeout

We cannot blame the PR for any of these though.
Do you agree to merge and then investigate these in parallel @shym?

**Comment by shym** [comment]
Indeed, I think we can merge it! :+1:

**Pull request merged**
