### PR TITLE
Weak test revisions

### PR DESCRIPTION
**Pull request by jmid**
This PR revises our `Weak` tests...

The `Weak` module depends on the state of the GC.
As such, we have to be extra careful to start from "as clean a starting point as possible".
Just having run sequential tests pollutes the heap state - so better run a `Gc.full_major ()` initially - and a cheaper `Gc.minor ()` in between attempts.

Secondly, the PR switches away from `string`s to more easy-to-shrink `int64`s.

Finally I think running `Lin` tests of `Weak` is misguided, as I don't think it makes sense to perform a fragile GC-dependent parallel run and compare its outputs against more fragile GC-dependent sequential runs.
Parallel `Weak` `STM` tests however work well as stress tests - we previously caught run-time bugs that way (e.g., #181)

Hopefully this will solve #299.

I can see a 5.2 s390x run even completed within the timelimit with this: :tada: 
https://ocaml-multicoretests.ci.dev:8100/job/2023-06-09/150708-ci-ocluster-build-44e4ee

### CODE REVIEW

**Comment by jmid** [comment]
The shadowing is handled in 9b85211.
I've also gone for removing the `Lin` tests entirely as I don't see us needing them in the future.
We may have to disable the parallel `src/weak/stm_tests_hashset` test on Windows bytecode where it doesn't seem to consistently trigger.

**Comment by jmid** [comment]
CI summary for 720028c
- a failure to trigger a parallel `weak/stm_tests_hashset` on Windows bytecode 5.1.0~alpha2
- a timeout due to excessive `Lin` `Ephemeron` shrinking on Cygwin part 1 5.1.0~alpha2
- a timeout due to excessive `Lin` `Out_channel` shrinking on Windows bytecode trunk 5.2
- a timeout due to `threadomain` livelock on Windows 5.1.0~alpha2 and on Windows trunk 5.2 #203 
- a timeout due to a on `domain_spawntree with Atomic` on Windows trunk 5.2 #354
- a timeout due to long-running `int ref STM` and `Thread` tests (several 1500+ secs) on Cygwin part 2 trunk 5.2
- a failure to trigger a `Lin` `Out_channel` test on Linux arm64 5.1 #360

Modulo the first one, none of this is related to this PR.

**Comment by shym** [comment]
Small suggestion for the last commit: rather than disabling the warning globally, it can be disabled only where it might trigger, it’s easier to understand why it is required.
```diff
@@ -41,6 +41,7 @@ struct
 
   module Int64 =
   struct
+    [@@@warning "-unused-value-declaration"]
     (* support Int64.hash added in 5.1 *)
     external seeded_hash_param :
       int -> int -> int -> 'a -> int = "caml_hash" [@@noalloc]
```

**Comment by jmid** [comment]
CI summary for the latest run:
- 1 Windows bytecode `5.1.0~alpha2` `threadomain` timeout and 1 crash - with a new variant #203
- 1 Windows bytecode trunk 5.2 unexpected `Thread` `Queue` counterexample #363 
- 2 timeouts on Cygwin part 1 `5.1` and 1 Linux s390x `5.1` due to several (primary `Lin`) tests taking 1000+ seconds
- 1 macOS arm64 `5.2` failure to trigger `STM int ref test parallel asymmetric` #364 

I'll go ahead and merge.

**Pull request merged**
